# Generated by Django 3.0.3 on 2020-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='المحافظة :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الهنوان بتفاصيل :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='الهاتف :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist_doctor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متخصص في :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='مده الانتظار :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='عدد ساعات العمل :'),
        ),
    ]
