# Generated by Django 3.0.3 on 2020-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200406_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default=1, max_length=60, verbose_name=' نبذه عنك'),
            preserve_default=False,
        ),
    ]
