# Generated by Django 3.0.3 on 2020-04-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200407_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gmail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gmail'),
        ),
    ]
