# Generated by Django 3.0.3 on 2020-04-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gmail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Gmail'),
        ),
    ]
