# Generated by Django 3.0.3 on 2020-04-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200407_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_us',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='وقت الانضمام :'),
            preserve_default=False,
        ),
    ]
