# Generated by Django 3.0.3 on 2020-04-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_join_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='وقت الانضمام :'),
            preserve_default=False,
        ),
    ]
