# Generated by Django 3.0.3 on 2020-04-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_join_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='join_new',
            new_name='join_niw',
        ),
    ]
