# Generated by Django 3.0.3 on 2020-04-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200407_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='join_niw',
            new_name='join_now',
        ),
    ]
