# Generated by Django 3.0.3 on 2020-04-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200407_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join_now',
        ),
        migrations.AddField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(default=1, verbose_name='وقت الانضمام :'),
            preserve_default=False,
        ),
    ]
