# Generated by Django 3.0.3 on 2020-04-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200407_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الانضمام :'),
        ),
    ]
